import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
//import getConfig from "next/config"

// I was trying to get user info by auth and still had bugs. 
// I have commented out the code of getting user info below.
// Hardcode the user's name and avatar on user.js.
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://localhost:3000">Newinstagram!</a>
        </h1>
        <p className={styles.description}>
          Get started by {' '}
          <code className={styles.code}>adding a new post!</code>
        </p>
        <div className={styles.grid}>   
            <div >
            <img class="inline-block h-10 w-10 rounded-full ring-2 ring-white" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToBpVYRRvT_C6iKp9fOVdbloPN3Nux-KGChQ&usqp=CAU" alt=""/>
            </div>
        </div>
        <Link href="/user">
        <button>Login</button>
        </Link>
      </main>
    </div>       
  )
}
//const {publicRuntimeConfig} = getConfig();

// export async function getServerSideProps() {

//   const loginInfo = {
//     identifier: 'mulan@gmail.com',
//     password: '123456'
//   }

//   const login = await fetch(`${publicRuntimeConfig.API_URL}/auth/local`, {
//     method: "POST",
//     headers: {
//       'Accept' : 'application/json' ,
//       'Content-Type:': 'application/json'
//     },
//     body: JSON.stringify(loginInfo)
//   })

//   const loginResponse = await login.json()

//   const res = await fetch(`${publicRuntimeConfig.API_URL}/followings`, {
//     headers: {
//       Authorization: `Bearer ${loginResponse.jwt}`
//     }
//   })
//   const followings = await res.json()

//   // Pass data to the page via props 
//   return { props: { 
//     followings : followings,
//     authData: loginResponse
//   } }
// }




